# Afrikaburn Community App
# Useing a the Nylo Micro-framework for Flutter.
#
# Website: https://afrikaburn.org
# Framework repository: https://github.com/nylo-core/nylo
# Author: Vince Kruger

name: afrikaburn
description: The community app for AfrikaBurn
publish_to: 'none'
version: 2024.0.0+5

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  nylo_framework: ^5.21.10
  url_launcher: ^6.2.5
  google_fonts: ^6.2.1
  analyzer: ^6.2.0
  intl: ^0.18.1
  pretty_dio_logger: ^1.3.1
  cupertino_icons: ^1.0.6
  flutter_cached_pdfview: ^0.4.2
  modal_bottom_sheet: ^3.0.0
  qr_flutter: ^4.1.0
  vcf_dart: ^1.0.1
  flutter_native_contact_picker: ^0.0.6
  firebase_core: ^2.27.1
  firebase_analytics: ^10.8.10
  firebase_crashlytics: ^3.4.19
  firebase_performance: ^0.9.3+18
  firebase_remote_config: ^4.3.18
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  photo_view: ^0.14.0
  shared_preferences: ^2.2.2
  mapbox_maps_flutter: ^1.0.0
  cloud_firestore: ^4.15.10
  outline_gradient_button: ^2.0.1+1
  page_transition: ^2.1.0
  flutter_html: ^3.0.0-beta.2
  moment_dart: ^2.0.2
  cached_network_image: ^3.3.1
  flashy_tab_bar2: ^0.0.10
  gradient_icon: ^2.0.9

dev_dependencies:
  lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Staatliches
      fonts:
        - asset: public/assets/fonts/Staatliches-Regular.ttf
    - family:  AB2024
      fonts:
        - asset: public/assets/flutter-icons/fonts/AB2024.ttf

  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/images/news/
    - public/assets/images/tickets/
    - public/assets/app_icon/
    - lang/
    - .env
