// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb, kReleaseMode;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if (kReleaseMode)
          throw UnsupportedError(
              'DefaultFirebaseOptions for Relase have not been configured for android');

        return androidDebug;
      case TargetPlatform.iOS:
        if (kReleaseMode) return iosRelease;
        return iosDebug;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidDebug = FirebaseOptions(
    apiKey: 'AIzaSyDPiW4KupYTBf8NTiDeGO3QcpxVBLRS7q0',
    appId: '1:700936341717:android:120f2b253c5fadcbdc7a5c',
    messagingSenderId: '700936341717',
    projectId: 'afrikaburn-dev',
    databaseURL: 'https://afrikaburn-dev.firebaseio.com',
    storageBucket: 'io.wheresmyshit.afrikaburn.debug',
  );

  static const FirebaseOptions iosDebug = FirebaseOptions(
    apiKey: 'AIzaSyDqmzd1DXLHyWzgrw_3ue8EJ-X8qNg8ot4',
    appId: '1:700936341717:ios:279c7d73b35ab765dc7a5c',
    messagingSenderId: '700936341717',
    projectId: 'afrikaburn-dev',
    databaseURL: 'https://afrikaburn-dev.firebaseio.com',
    storageBucket: 'afrikaburn-dev.appspot.com',
    iosBundleId: 'io.wheresmyshit.afrikaburn.debug',
  );

  static const FirebaseOptions iosRelease = FirebaseOptions(
    apiKey: 'AIzaSyAiCwczgOo37F2irJnuMEyYeZ_xMFcQm28',
    appId: '1:1070999950214:ios:fbb43063c274316e369207',
    messagingSenderId: '1070999950214',
    projectId: 'afrikaburn-35158',
    databaseURL: 'https://afrikaburn-35158.firebaseio.com',
    storageBucket: 'afrikaburn-35158.appspot.com',
    iosBundleId: 'io.wheresmyshit.afrikaburn',
  );
}
