/// Flutter icons AB2024
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AB2024
///      fonts:
///       - asset: fonts/AB2024.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AB2024 {
  AB2024._();

  static const _kFontFam = 'AB2024';
  static const String? _kFontPkg = null;

  static const IconData ticket_add_entry = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_add_entry_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_remove_entry = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_view_entry = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_thick = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
