/// Flutter icons AB2024
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AB2024
///      fonts:
///       - asset: fonts/AB2024.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AB2024 {
  AB2024._();

  static const _kFontFam = 'AB2024';
  static const String? _kFontPkg = null;

  static const IconData ticket_add_entry = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_add_entry_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_remove_entry = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_view_entry = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_thick = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData art = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mutant_vehicle = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rft = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_camp = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wtf_guide = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contribute = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburger = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData off_slash = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
