/// Flutter icons AB24Icons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AB24Icons
///      fonts:
///       - asset: fonts/AB24Icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AB24Icons {
  AB24Icons._();

  static const _kFontFam = 'AB24Icons';
  static const String? _kFontPkg = null;

  static const IconData art = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adjust_brightness = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change_contact = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right_compact = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_thick = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_thin = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contribute = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburger = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mutant_vehicle = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData off_slash = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_think = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rft = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme_camp = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_remove_entry = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wtf_guide = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_tick = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rft_compact = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
